version: '2'
services:
  web:
    image: sinso/nginx:latest
    ports:
      - 80:80
    environment:
      PHPFPM_ENV_APPLICATION_TYPE: TYPO3_8
      VIRTUAL_HOST: domain.dev
      PHPFPM_PORT_9000_TCP_PORT: 9000
      USERID: 1000
      USER: user
      GROUPID: 50
      GROUP: group
    volumes:
      - /var/data/projekt:/data/web/releases/current
      - /var/data/projekt/docker/log:/data/log
      - /var/data/projekt/docker/nginx/custom:/etc/nginx/conf.d/custom
    links:
      - phpfpm

  phpfpm:
    image: sinso/phpfpm-flow-dev:latest
    environment:
      APPLICATION_TYPE: TYPO3_8 
      TYPO3_CONTEXT: Development
      DOMAIN_LIST: domain.dev,domain2.dev
      PRIMARY_DOMAIN: domain.dev
      PRIMARY_SCHEMA: http
      SSMTP_ROOT: 
      SSMTP_MAILHUB: 
      SSMTP_HOSTNAME:
      IMPORT_MYSQL_DUMP: dump.sql
      USERID: 1000
      USER: user
      GROUPID: 50
      GROUP: group
      SSH_AUTH_SOCK: /ssh-agent
      DB_HOST: db
      DB_ENV_MYSQL_DATABASE: database
      DB_ENV_MYSQL_USER: db-user
      DB_ENV_MYSQL_PASSWORD: docker
      DB_PORT_3306_TCP_PORT: 3306
      DB_PASSWORD: docker
    volumes:
      - /var/data/projekt:/data/web/releases/current
      - /var/data/projekt/docker/log:/data/log
      - /var/data/projekt/docker/cron.d:/etc/cron.d
      - /var/data/projekt/docker/ca-certificates:/usr/local/share/ca-certificates
      - $SSH_AUTH_SOCK:/ssh-agent
    links:
      - db
      - solr

  db:
    image: sinso/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: database
      MYSQL_USER: db-user
      MYSQL_PASSWORD: docker
      USERID: 1000
      USER: mysql
      GROUPID: 50
      GROUP: mysql
    volumes:
      - /var/data/projekt/docker/mysql:/var/lib/mysql
      - /var/data/projekt/docker/log:/data/log

  solr:
    image: sinso/solr-typo3-bjb:dev
    ports:
      - 8983:8983
    volumes:
      - /var/data/projekt/docker/solr:/opt/solr/server/solr/data
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
        - "1025:1025"
        - "8025:8025"
